package com.trpg.version1.mybatis.entity;

import java.io.Serializable;

public class Attribute implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.attributeId
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    private Integer attributeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.name
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.descri
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    private String descri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute.state
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.attributeId
     *
     * @return the value of attribute.attributeId
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    public Integer getAttributeid() {
        return attributeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.attributeId
     *
     * @param attributeid the value for attribute.attributeId
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    public void setAttributeid(Integer attributeid) {
        this.attributeid = attributeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.name
     *
     * @return the value of attribute.name
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.name
     *
     * @param name the value for attribute.name
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.descri
     *
     * @return the value of attribute.descri
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    public String getDescri() {
        return descri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.descri
     *
     * @param descri the value for attribute.descri
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    public void setDescri(String descri) {
        this.descri = descri == null ? null : descri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute.state
     *
     * @return the value of attribute.state
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute.state
     *
     * @param state the value for attribute.state
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", attributeid=").append(attributeid);
        sb.append(", name=").append(name);
        sb.append(", descri=").append(descri);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}