package com.trpg.version1.mybatis.entity;

import java.io.Serializable;

public class Charact implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.characterId
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    private Integer characterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.userId
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.name
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.sex
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.age
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.time
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.resident
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    private String resident;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.home
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    private String home;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.state
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charact
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.characterId
     *
     * @return the value of charact.characterId
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public Integer getCharacterid() {
        return characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.characterId
     *
     * @param characterid the value for charact.characterId
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public void setCharacterid(Integer characterid) {
        this.characterid = characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.userId
     *
     * @return the value of charact.userId
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.userId
     *
     * @param userid the value for charact.userId
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.name
     *
     * @return the value of charact.name
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.name
     *
     * @param name the value for charact.name
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.sex
     *
     * @return the value of charact.sex
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.sex
     *
     * @param sex the value for charact.sex
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.age
     *
     * @return the value of charact.age
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.age
     *
     * @param age the value for charact.age
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.time
     *
     * @return the value of charact.time
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.time
     *
     * @param time the value for charact.time
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.resident
     *
     * @return the value of charact.resident
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public String getResident() {
        return resident;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.resident
     *
     * @param resident the value for charact.resident
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public void setResident(String resident) {
        this.resident = resident == null ? null : resident.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.home
     *
     * @return the value of charact.home
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public String getHome() {
        return home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.home
     *
     * @param home the value for charact.home
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public void setHome(String home) {
        this.home = home == null ? null : home.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.state
     *
     * @return the value of charact.state
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.state
     *
     * @param state the value for charact.state
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charact
     *
     * @mbg.generated Sat Jun 19 03:53:06 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", characterid=").append(characterid);
        sb.append(", userid=").append(userid);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", age=").append(age);
        sb.append(", time=").append(time);
        sb.append(", resident=").append(resident);
        sb.append(", home=").append(home);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}