package com.trpg.version1.mybatis.entity;

import java.io.Serializable;

public class CharacterRoom implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column characterRoom.characterId
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    private Integer characterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column characterRoom.userId
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column characterRoom.roomId
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    private Integer roomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column characterRoom.state
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table characterRoom
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column characterRoom.characterId
     *
     * @return the value of characterRoom.characterId
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    public Integer getCharacterid() {
        return characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column characterRoom.characterId
     *
     * @param characterid the value for characterRoom.characterId
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    public void setCharacterid(Integer characterid) {
        this.characterid = characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column characterRoom.userId
     *
     * @return the value of characterRoom.userId
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column characterRoom.userId
     *
     * @param userid the value for characterRoom.userId
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column characterRoom.roomId
     *
     * @return the value of characterRoom.roomId
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column characterRoom.roomId
     *
     * @param roomid the value for characterRoom.roomId
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column characterRoom.state
     *
     * @return the value of characterRoom.state
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column characterRoom.state
     *
     * @param state the value for characterRoom.state
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table characterRoom
     *
     * @mbg.generated Sun Jun 13 03:05:19 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", characterid=").append(characterid);
        sb.append(", userid=").append(userid);
        sb.append(", roomid=").append(roomid);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}