package com.trpg.version1.mybatis.entity;

import java.io.Serializable;

public class Charact implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.characterId
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    private Integer characterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.userId
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.name
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.demage
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    private String demage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.isElligibleToEnroll
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    private String iselligibletoenroll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.getSeminarsTaken
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    private String getseminarstaken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column charact.state
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charact
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.characterId
     *
     * @return the value of charact.characterId
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public Integer getCharacterid() {
        return characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.characterId
     *
     * @param characterid the value for charact.characterId
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public void setCharacterid(Integer characterid) {
        this.characterid = characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.userId
     *
     * @return the value of charact.userId
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.userId
     *
     * @param userid the value for charact.userId
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.name
     *
     * @return the value of charact.name
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.name
     *
     * @param name the value for charact.name
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.demage
     *
     * @return the value of charact.demage
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public String getDemage() {
        return demage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.demage
     *
     * @param demage the value for charact.demage
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public void setDemage(String demage) {
        this.demage = demage == null ? null : demage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.isElligibleToEnroll
     *
     * @return the value of charact.isElligibleToEnroll
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public String getIselligibletoenroll() {
        return iselligibletoenroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.isElligibleToEnroll
     *
     * @param iselligibletoenroll the value for charact.isElligibleToEnroll
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public void setIselligibletoenroll(String iselligibletoenroll) {
        this.iselligibletoenroll = iselligibletoenroll == null ? null : iselligibletoenroll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.getSeminarsTaken
     *
     * @return the value of charact.getSeminarsTaken
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public String getGetseminarstaken() {
        return getseminarstaken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.getSeminarsTaken
     *
     * @param getseminarstaken the value for charact.getSeminarsTaken
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public void setGetseminarstaken(String getseminarstaken) {
        this.getseminarstaken = getseminarstaken == null ? null : getseminarstaken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column charact.state
     *
     * @return the value of charact.state
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column charact.state
     *
     * @param state the value for charact.state
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charact
     *
     * @mbg.generated Mon Jun 14 23:21:26 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", characterid=").append(characterid);
        sb.append(", userid=").append(userid);
        sb.append(", name=").append(name);
        sb.append(", demage=").append(demage);
        sb.append(", iselligibletoenroll=").append(iselligibletoenroll);
        sb.append(", getseminarstaken=").append(getseminarstaken);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}