package com.trpg.version1.mybatis.entity;

import java.io.Serializable;

public class Character implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.characterId
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private Integer characterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.userId
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.isElligibleToEnroll
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private String iselligibletoenroll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.getSeminarsTaken
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private String getseminarstaken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.state
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table character
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.characterId
     *
     * @return the value of character.characterId
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public Integer getCharacterid() {
        return characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.characterId
     *
     * @param characterid the value for character.characterId
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public void setCharacterid(Integer characterid) {
        this.characterid = characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.userId
     *
     * @return the value of character.userId
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.userId
     *
     * @param userid the value for character.userId
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.isElligibleToEnroll
     *
     * @return the value of character.isElligibleToEnroll
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public String getIselligibletoenroll() {
        return iselligibletoenroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.isElligibleToEnroll
     *
     * @param iselligibletoenroll the value for character.isElligibleToEnroll
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public void setIselligibletoenroll(String iselligibletoenroll) {
        this.iselligibletoenroll = iselligibletoenroll == null ? null : iselligibletoenroll.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.getSeminarsTaken
     *
     * @return the value of character.getSeminarsTaken
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public String getGetseminarstaken() {
        return getseminarstaken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.getSeminarsTaken
     *
     * @param getseminarstaken the value for character.getSeminarsTaken
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public void setGetseminarstaken(String getseminarstaken) {
        this.getseminarstaken = getseminarstaken == null ? null : getseminarstaken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.state
     *
     * @return the value of character.state
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.state
     *
     * @param state the value for character.state
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", characterid=").append(characterid);
        sb.append(", userid=").append(userid);
        sb.append(", iselligibletoenroll=").append(iselligibletoenroll);
        sb.append(", getseminarstaken=").append(getseminarstaken);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}