package com.trpg.version1.mybatis.entity;

import java.io.Serializable;

public class CommentUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentUser.userId
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentUser.userIdTarget
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private Integer useridtarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentUser.score
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentUser.comment
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentUser.state
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commentUser
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentUser.userId
     *
     * @return the value of commentUser.userId
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentUser.userId
     *
     * @param userid the value for commentUser.userId
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentUser.userIdTarget
     *
     * @return the value of commentUser.userIdTarget
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public Integer getUseridtarget() {
        return useridtarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentUser.userIdTarget
     *
     * @param useridtarget the value for commentUser.userIdTarget
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public void setUseridtarget(Integer useridtarget) {
        this.useridtarget = useridtarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentUser.score
     *
     * @return the value of commentUser.score
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentUser.score
     *
     * @param score the value for commentUser.score
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentUser.comment
     *
     * @return the value of commentUser.comment
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentUser.comment
     *
     * @param comment the value for commentUser.comment
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentUser.state
     *
     * @return the value of commentUser.state
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentUser.state
     *
     * @param state the value for commentUser.state
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentUser
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", useridtarget=").append(useridtarget);
        sb.append(", score=").append(score);
        sb.append(", comment=").append(comment);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}