package com.trpg.version1.mybatis.entity;

import java.io.Serializable;

public class Item implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.itemId
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.characterId
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    private Integer characterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.num
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.descri
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    private String descri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.state
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.itemId
     *
     * @return the value of item.itemId
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.itemId
     *
     * @param itemid the value for item.itemId
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.characterId
     *
     * @return the value of item.characterId
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public Integer getCharacterid() {
        return characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.characterId
     *
     * @param characterid the value for item.characterId
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public void setCharacterid(Integer characterid) {
        this.characterid = characterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.num
     *
     * @return the value of item.num
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.num
     *
     * @param num the value for item.num
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.descri
     *
     * @return the value of item.descri
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public String getDescri() {
        return descri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.descri
     *
     * @param descri the value for item.descri
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public void setDescri(String descri) {
        this.descri = descri == null ? null : descri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.state
     *
     * @return the value of item.state
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.state
     *
     * @param state the value for item.state
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", itemid=").append(itemid);
        sb.append(", characterid=").append(characterid);
        sb.append(", name=").append(name);
        sb.append(", num=").append(num);
        sb.append(", descri=").append(descri);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}