package com.trpg.version1.mybatis.entity;

import java.io.Serializable;

public class LabelModule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labelModule.mid
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labelModule.labelId
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    private Integer labelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column labelModule.state
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table labelModule
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labelModule.mid
     *
     * @return the value of labelModule.mid
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labelModule.mid
     *
     * @param mid the value for labelModule.mid
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labelModule.labelId
     *
     * @return the value of labelModule.labelId
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    public Integer getLabelid() {
        return labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labelModule.labelId
     *
     * @param labelid the value for labelModule.labelId
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    public void setLabelid(Integer labelid) {
        this.labelid = labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column labelModule.state
     *
     * @return the value of labelModule.state
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column labelModule.state
     *
     * @param state the value for labelModule.state
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table labelModule
     *
     * @mbg.generated Tue Jun 08 23:12:34 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mid=").append(mid);
        sb.append(", labelid=").append(labelid);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}