package com.trpg.version1.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class ModuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public ModuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMidIsNull() {
            addCriterion("mid is null");
            return (Criteria) this;
        }

        public Criteria andMidIsNotNull() {
            addCriterion("mid is not null");
            return (Criteria) this;
        }

        public Criteria andMidEqualTo(Integer value) {
            addCriterion("mid =", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotEqualTo(Integer value) {
            addCriterion("mid <>", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThan(Integer value) {
            addCriterion("mid >", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThanOrEqualTo(Integer value) {
            addCriterion("mid >=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThan(Integer value) {
            addCriterion("mid <", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThanOrEqualTo(Integer value) {
            addCriterion("mid <=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidIn(List<Integer> values) {
            addCriterion("mid in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotIn(List<Integer> values) {
            addCriterion("mid not in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidBetween(Integer value1, Integer value2) {
            addCriterion("mid between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotBetween(Integer value1, Integer value2) {
            addCriterion("mid not between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriIsNull() {
            addCriterion("descri is null");
            return (Criteria) this;
        }

        public Criteria andDescriIsNotNull() {
            addCriterion("descri is not null");
            return (Criteria) this;
        }

        public Criteria andDescriEqualTo(String value) {
            addCriterion("descri =", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriNotEqualTo(String value) {
            addCriterion("descri <>", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriGreaterThan(String value) {
            addCriterion("descri >", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriGreaterThanOrEqualTo(String value) {
            addCriterion("descri >=", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriLessThan(String value) {
            addCriterion("descri <", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriLessThanOrEqualTo(String value) {
            addCriterion("descri <=", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriLike(String value) {
            addCriterion("descri like", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriNotLike(String value) {
            addCriterion("descri not like", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriIn(List<String> values) {
            addCriterion("descri in", values, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriNotIn(List<String> values) {
            addCriterion("descri not in", values, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriBetween(String value1, String value2) {
            addCriterion("descri between", value1, value2, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriNotBetween(String value1, String value2) {
            addCriterion("descri not between", value1, value2, "descri");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andShorttimeIsNull() {
            addCriterion("shortTime is null");
            return (Criteria) this;
        }

        public Criteria andShorttimeIsNotNull() {
            addCriterion("shortTime is not null");
            return (Criteria) this;
        }

        public Criteria andShorttimeEqualTo(String value) {
            addCriterion("shortTime =", value, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeNotEqualTo(String value) {
            addCriterion("shortTime <>", value, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeGreaterThan(String value) {
            addCriterion("shortTime >", value, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeGreaterThanOrEqualTo(String value) {
            addCriterion("shortTime >=", value, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeLessThan(String value) {
            addCriterion("shortTime <", value, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeLessThanOrEqualTo(String value) {
            addCriterion("shortTime <=", value, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeLike(String value) {
            addCriterion("shortTime like", value, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeNotLike(String value) {
            addCriterion("shortTime not like", value, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeIn(List<String> values) {
            addCriterion("shortTime in", values, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeNotIn(List<String> values) {
            addCriterion("shortTime not in", values, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeBetween(String value1, String value2) {
            addCriterion("shortTime between", value1, value2, "shorttime");
            return (Criteria) this;
        }

        public Criteria andShorttimeNotBetween(String value1, String value2) {
            addCriterion("shortTime not between", value1, value2, "shorttime");
            return (Criteria) this;
        }

        public Criteria andLongtimeIsNull() {
            addCriterion("longTime is null");
            return (Criteria) this;
        }

        public Criteria andLongtimeIsNotNull() {
            addCriterion("longTime is not null");
            return (Criteria) this;
        }

        public Criteria andLongtimeEqualTo(String value) {
            addCriterion("longTime =", value, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeNotEqualTo(String value) {
            addCriterion("longTime <>", value, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeGreaterThan(String value) {
            addCriterion("longTime >", value, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeGreaterThanOrEqualTo(String value) {
            addCriterion("longTime >=", value, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeLessThan(String value) {
            addCriterion("longTime <", value, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeLessThanOrEqualTo(String value) {
            addCriterion("longTime <=", value, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeLike(String value) {
            addCriterion("longTime like", value, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeNotLike(String value) {
            addCriterion("longTime not like", value, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeIn(List<String> values) {
            addCriterion("longTime in", values, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeNotIn(List<String> values) {
            addCriterion("longTime not in", values, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeBetween(String value1, String value2) {
            addCriterion("longTime between", value1, value2, "longtime");
            return (Criteria) this;
        }

        public Criteria andLongtimeNotBetween(String value1, String value2) {
            addCriterion("longTime not between", value1, value2, "longtime");
            return (Criteria) this;
        }

        public Criteria andFileurlIsNull() {
            addCriterion("fileUrl is null");
            return (Criteria) this;
        }

        public Criteria andFileurlIsNotNull() {
            addCriterion("fileUrl is not null");
            return (Criteria) this;
        }

        public Criteria andFileurlEqualTo(String value) {
            addCriterion("fileUrl =", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlNotEqualTo(String value) {
            addCriterion("fileUrl <>", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlGreaterThan(String value) {
            addCriterion("fileUrl >", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlGreaterThanOrEqualTo(String value) {
            addCriterion("fileUrl >=", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlLessThan(String value) {
            addCriterion("fileUrl <", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlLessThanOrEqualTo(String value) {
            addCriterion("fileUrl <=", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlLike(String value) {
            addCriterion("fileUrl like", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlNotLike(String value) {
            addCriterion("fileUrl not like", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlIn(List<String> values) {
            addCriterion("fileUrl in", values, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlNotIn(List<String> values) {
            addCriterion("fileUrl not in", values, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlBetween(String value1, String value2) {
            addCriterion("fileUrl between", value1, value2, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlNotBetween(String value1, String value2) {
            addCriterion("fileUrl not between", value1, value2, "fileurl");
            return (Criteria) this;
        }

        public Criteria andRuletypeIsNull() {
            addCriterion("ruleType is null");
            return (Criteria) this;
        }

        public Criteria andRuletypeIsNotNull() {
            addCriterion("ruleType is not null");
            return (Criteria) this;
        }

        public Criteria andRuletypeEqualTo(String value) {
            addCriterion("ruleType =", value, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeNotEqualTo(String value) {
            addCriterion("ruleType <>", value, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeGreaterThan(String value) {
            addCriterion("ruleType >", value, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeGreaterThanOrEqualTo(String value) {
            addCriterion("ruleType >=", value, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeLessThan(String value) {
            addCriterion("ruleType <", value, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeLessThanOrEqualTo(String value) {
            addCriterion("ruleType <=", value, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeLike(String value) {
            addCriterion("ruleType like", value, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeNotLike(String value) {
            addCriterion("ruleType not like", value, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeIn(List<String> values) {
            addCriterion("ruleType in", values, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeNotIn(List<String> values) {
            addCriterion("ruleType not in", values, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeBetween(String value1, String value2) {
            addCriterion("ruleType between", value1, value2, "ruletype");
            return (Criteria) this;
        }

        public Criteria andRuletypeNotBetween(String value1, String value2) {
            addCriterion("ruleType not between", value1, value2, "ruletype");
            return (Criteria) this;
        }

        public Criteria andTimepublishIsNull() {
            addCriterion("timePublish is null");
            return (Criteria) this;
        }

        public Criteria andTimepublishIsNotNull() {
            addCriterion("timePublish is not null");
            return (Criteria) this;
        }

        public Criteria andTimepublishEqualTo(String value) {
            addCriterion("timePublish =", value, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishNotEqualTo(String value) {
            addCriterion("timePublish <>", value, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishGreaterThan(String value) {
            addCriterion("timePublish >", value, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishGreaterThanOrEqualTo(String value) {
            addCriterion("timePublish >=", value, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishLessThan(String value) {
            addCriterion("timePublish <", value, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishLessThanOrEqualTo(String value) {
            addCriterion("timePublish <=", value, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishLike(String value) {
            addCriterion("timePublish like", value, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishNotLike(String value) {
            addCriterion("timePublish not like", value, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishIn(List<String> values) {
            addCriterion("timePublish in", values, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishNotIn(List<String> values) {
            addCriterion("timePublish not in", values, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishBetween(String value1, String value2) {
            addCriterion("timePublish between", value1, value2, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimepublishNotBetween(String value1, String value2) {
            addCriterion("timePublish not between", value1, value2, "timepublish");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundIsNull() {
            addCriterion("timeBackground is null");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundIsNotNull() {
            addCriterion("timeBackground is not null");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundEqualTo(String value) {
            addCriterion("timeBackground =", value, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundNotEqualTo(String value) {
            addCriterion("timeBackground <>", value, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundGreaterThan(String value) {
            addCriterion("timeBackground >", value, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundGreaterThanOrEqualTo(String value) {
            addCriterion("timeBackground >=", value, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundLessThan(String value) {
            addCriterion("timeBackground <", value, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundLessThanOrEqualTo(String value) {
            addCriterion("timeBackground <=", value, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundLike(String value) {
            addCriterion("timeBackground like", value, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundNotLike(String value) {
            addCriterion("timeBackground not like", value, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundIn(List<String> values) {
            addCriterion("timeBackground in", values, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundNotIn(List<String> values) {
            addCriterion("timeBackground not in", values, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundBetween(String value1, String value2) {
            addCriterion("timeBackground between", value1, value2, "timebackground");
            return (Criteria) this;
        }

        public Criteria andTimebackgroundNotBetween(String value1, String value2) {
            addCriterion("timeBackground not between", value1, value2, "timebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundIsNull() {
            addCriterion("placeBackground is null");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundIsNotNull() {
            addCriterion("placeBackground is not null");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundEqualTo(String value) {
            addCriterion("placeBackground =", value, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundNotEqualTo(String value) {
            addCriterion("placeBackground <>", value, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundGreaterThan(String value) {
            addCriterion("placeBackground >", value, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundGreaterThanOrEqualTo(String value) {
            addCriterion("placeBackground >=", value, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundLessThan(String value) {
            addCriterion("placeBackground <", value, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundLessThanOrEqualTo(String value) {
            addCriterion("placeBackground <=", value, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundLike(String value) {
            addCriterion("placeBackground like", value, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundNotLike(String value) {
            addCriterion("placeBackground not like", value, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundIn(List<String> values) {
            addCriterion("placeBackground in", values, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundNotIn(List<String> values) {
            addCriterion("placeBackground not in", values, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundBetween(String value1, String value2) {
            addCriterion("placeBackground between", value1, value2, "placebackground");
            return (Criteria) this;
        }

        public Criteria andPlacebackgroundNotBetween(String value1, String value2) {
            addCriterion("placeBackground not between", value1, value2, "placebackground");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleIsNull() {
            addCriterion("recommendPeople is null");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleIsNotNull() {
            addCriterion("recommendPeople is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleEqualTo(String value) {
            addCriterion("recommendPeople =", value, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleNotEqualTo(String value) {
            addCriterion("recommendPeople <>", value, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleGreaterThan(String value) {
            addCriterion("recommendPeople >", value, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleGreaterThanOrEqualTo(String value) {
            addCriterion("recommendPeople >=", value, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleLessThan(String value) {
            addCriterion("recommendPeople <", value, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleLessThanOrEqualTo(String value) {
            addCriterion("recommendPeople <=", value, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleLike(String value) {
            addCriterion("recommendPeople like", value, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleNotLike(String value) {
            addCriterion("recommendPeople not like", value, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleIn(List<String> values) {
            addCriterion("recommendPeople in", values, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleNotIn(List<String> values) {
            addCriterion("recommendPeople not in", values, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleBetween(String value1, String value2) {
            addCriterion("recommendPeople between", value1, value2, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andRecommendpeopleNotBetween(String value1, String value2) {
            addCriterion("recommendPeople not between", value1, value2, "recommendpeople");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table modulle
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 09 01:02:42 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}