package com.trpg.version1.mybatis.entity;

import java.io.Serializable;

public class Module implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.mid
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private Integer mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.userId
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.name
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.descri
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String descri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.type
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.shortTime
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String shorttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.longTime
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String longtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.fileUrl
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String fileurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.ruleType
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String ruletype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.timePublish
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String timepublish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.timeBackground
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String timebackground;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.placeBackground
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String placebackground;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.recommendPeople
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private String recommendpeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modulle.state
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.mid
     *
     * @return the value of modulle.mid
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.mid
     *
     * @param mid the value for modulle.mid
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.userId
     *
     * @return the value of modulle.userId
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.userId
     *
     * @param userid the value for modulle.userId
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.name
     *
     * @return the value of modulle.name
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.name
     *
     * @param name the value for modulle.name
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.descri
     *
     * @return the value of modulle.descri
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getDescri() {
        return descri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.descri
     *
     * @param descri the value for modulle.descri
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setDescri(String descri) {
        this.descri = descri == null ? null : descri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.type
     *
     * @return the value of modulle.type
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.type
     *
     * @param type the value for modulle.type
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.shortTime
     *
     * @return the value of modulle.shortTime
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getShorttime() {
        return shorttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.shortTime
     *
     * @param shorttime the value for modulle.shortTime
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setShorttime(String shorttime) {
        this.shorttime = shorttime == null ? null : shorttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.longTime
     *
     * @return the value of modulle.longTime
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getLongtime() {
        return longtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.longTime
     *
     * @param longtime the value for modulle.longTime
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setLongtime(String longtime) {
        this.longtime = longtime == null ? null : longtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.fileUrl
     *
     * @return the value of modulle.fileUrl
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getFileurl() {
        return fileurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.fileUrl
     *
     * @param fileurl the value for modulle.fileUrl
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setFileurl(String fileurl) {
        this.fileurl = fileurl == null ? null : fileurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.ruleType
     *
     * @return the value of modulle.ruleType
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getRuletype() {
        return ruletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.ruleType
     *
     * @param ruletype the value for modulle.ruleType
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setRuletype(String ruletype) {
        this.ruletype = ruletype == null ? null : ruletype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.timePublish
     *
     * @return the value of modulle.timePublish
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getTimepublish() {
        return timepublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.timePublish
     *
     * @param timepublish the value for modulle.timePublish
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setTimepublish(String timepublish) {
        this.timepublish = timepublish == null ? null : timepublish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.timeBackground
     *
     * @return the value of modulle.timeBackground
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getTimebackground() {
        return timebackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.timeBackground
     *
     * @param timebackground the value for modulle.timeBackground
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setTimebackground(String timebackground) {
        this.timebackground = timebackground == null ? null : timebackground.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.placeBackground
     *
     * @return the value of modulle.placeBackground
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getPlacebackground() {
        return placebackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.placeBackground
     *
     * @param placebackground the value for modulle.placeBackground
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setPlacebackground(String placebackground) {
        this.placebackground = placebackground == null ? null : placebackground.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.recommendPeople
     *
     * @return the value of modulle.recommendPeople
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public String getRecommendpeople() {
        return recommendpeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.recommendPeople
     *
     * @param recommendpeople the value for modulle.recommendPeople
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setRecommendpeople(String recommendpeople) {
        this.recommendpeople = recommendpeople == null ? null : recommendpeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modulle.state
     *
     * @return the value of modulle.state
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modulle.state
     *
     * @param state the value for modulle.state
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modulle
     *
     * @mbg.generated Wed Jun 09 01:02:42 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mid=").append(mid);
        sb.append(", userid=").append(userid);
        sb.append(", name=").append(name);
        sb.append(", descri=").append(descri);
        sb.append(", type=").append(type);
        sb.append(", shorttime=").append(shorttime);
        sb.append(", longtime=").append(longtime);
        sb.append(", fileurl=").append(fileurl);
        sb.append(", ruletype=").append(ruletype);
        sb.append(", timepublish=").append(timepublish);
        sb.append(", timebackground=").append(timebackground);
        sb.append(", placebackground=").append(placebackground);
        sb.append(", recommendpeople=").append(recommendpeople);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}