package com.trpg.version1.mybatis.entity;

import java.util.ArrayList;
import java.util.List;

public class RoomExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public RoomExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoomidIsNull() {
            addCriterion("roomId is null");
            return (Criteria) this;
        }

        public Criteria andRoomidIsNotNull() {
            addCriterion("roomId is not null");
            return (Criteria) this;
        }

        public Criteria andRoomidEqualTo(Integer value) {
            addCriterion("roomId =", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotEqualTo(Integer value) {
            addCriterion("roomId <>", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThan(Integer value) {
            addCriterion("roomId >", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThanOrEqualTo(Integer value) {
            addCriterion("roomId >=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThan(Integer value) {
            addCriterion("roomId <", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThanOrEqualTo(Integer value) {
            addCriterion("roomId <=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidIn(List<Integer> values) {
            addCriterion("roomId in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotIn(List<Integer> values) {
            addCriterion("roomId not in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidBetween(Integer value1, Integer value2) {
            addCriterion("roomId between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotBetween(Integer value1, Integer value2) {
            addCriterion("roomId not between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriIsNull() {
            addCriterion("descri is null");
            return (Criteria) this;
        }

        public Criteria andDescriIsNotNull() {
            addCriterion("descri is not null");
            return (Criteria) this;
        }

        public Criteria andDescriEqualTo(String value) {
            addCriterion("descri =", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriNotEqualTo(String value) {
            addCriterion("descri <>", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriGreaterThan(String value) {
            addCriterion("descri >", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriGreaterThanOrEqualTo(String value) {
            addCriterion("descri >=", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriLessThan(String value) {
            addCriterion("descri <", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriLessThanOrEqualTo(String value) {
            addCriterion("descri <=", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriLike(String value) {
            addCriterion("descri like", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriNotLike(String value) {
            addCriterion("descri not like", value, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriIn(List<String> values) {
            addCriterion("descri in", values, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriNotIn(List<String> values) {
            addCriterion("descri not in", values, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriBetween(String value1, String value2) {
            addCriterion("descri between", value1, value2, "descri");
            return (Criteria) this;
        }

        public Criteria andDescriNotBetween(String value1, String value2) {
            addCriterion("descri not between", value1, value2, "descri");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andShortTimeIsNull() {
            addCriterion("short_Time is null");
            return (Criteria) this;
        }

        public Criteria andShortTimeIsNotNull() {
            addCriterion("short_Time is not null");
            return (Criteria) this;
        }

        public Criteria andShortTimeEqualTo(String value) {
            addCriterion("short_Time =", value, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeNotEqualTo(String value) {
            addCriterion("short_Time <>", value, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeGreaterThan(String value) {
            addCriterion("short_Time >", value, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeGreaterThanOrEqualTo(String value) {
            addCriterion("short_Time >=", value, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeLessThan(String value) {
            addCriterion("short_Time <", value, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeLessThanOrEqualTo(String value) {
            addCriterion("short_Time <=", value, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeLike(String value) {
            addCriterion("short_Time like", value, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeNotLike(String value) {
            addCriterion("short_Time not like", value, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeIn(List<String> values) {
            addCriterion("short_Time in", values, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeNotIn(List<String> values) {
            addCriterion("short_Time not in", values, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeBetween(String value1, String value2) {
            addCriterion("short_Time between", value1, value2, "shortTime");
            return (Criteria) this;
        }

        public Criteria andShortTimeNotBetween(String value1, String value2) {
            addCriterion("short_Time not between", value1, value2, "shortTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeIsNull() {
            addCriterion("long_Time is null");
            return (Criteria) this;
        }

        public Criteria andLongTimeIsNotNull() {
            addCriterion("long_Time is not null");
            return (Criteria) this;
        }

        public Criteria andLongTimeEqualTo(String value) {
            addCriterion("long_Time =", value, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeNotEqualTo(String value) {
            addCriterion("long_Time <>", value, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeGreaterThan(String value) {
            addCriterion("long_Time >", value, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeGreaterThanOrEqualTo(String value) {
            addCriterion("long_Time >=", value, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeLessThan(String value) {
            addCriterion("long_Time <", value, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeLessThanOrEqualTo(String value) {
            addCriterion("long_Time <=", value, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeLike(String value) {
            addCriterion("long_Time like", value, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeNotLike(String value) {
            addCriterion("long_Time not like", value, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeIn(List<String> values) {
            addCriterion("long_Time in", values, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeNotIn(List<String> values) {
            addCriterion("long_Time not in", values, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeBetween(String value1, String value2) {
            addCriterion("long_Time between", value1, value2, "longTime");
            return (Criteria) this;
        }

        public Criteria andLongTimeNotBetween(String value1, String value2) {
            addCriterion("long_Time not between", value1, value2, "longTime");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNull() {
            addCriterion("image_Url is null");
            return (Criteria) this;
        }

        public Criteria andImageUrlIsNotNull() {
            addCriterion("image_Url is not null");
            return (Criteria) this;
        }

        public Criteria andImageUrlEqualTo(String value) {
            addCriterion("image_Url =", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotEqualTo(String value) {
            addCriterion("image_Url <>", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThan(String value) {
            addCriterion("image_Url >", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("image_Url >=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThan(String value) {
            addCriterion("image_Url <", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLessThanOrEqualTo(String value) {
            addCriterion("image_Url <=", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlLike(String value) {
            addCriterion("image_Url like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotLike(String value) {
            addCriterion("image_Url not like", value, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlIn(List<String> values) {
            addCriterion("image_Url in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotIn(List<String> values) {
            addCriterion("image_Url not in", values, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlBetween(String value1, String value2) {
            addCriterion("image_Url between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andImageUrlNotBetween(String value1, String value2) {
            addCriterion("image_Url not between", value1, value2, "imageUrl");
            return (Criteria) this;
        }

        public Criteria andRuleTypeIsNull() {
            addCriterion("rule_Type is null");
            return (Criteria) this;
        }

        public Criteria andRuleTypeIsNotNull() {
            addCriterion("rule_Type is not null");
            return (Criteria) this;
        }

        public Criteria andRuleTypeEqualTo(String value) {
            addCriterion("rule_Type =", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotEqualTo(String value) {
            addCriterion("rule_Type <>", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeGreaterThan(String value) {
            addCriterion("rule_Type >", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("rule_Type >=", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeLessThan(String value) {
            addCriterion("rule_Type <", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeLessThanOrEqualTo(String value) {
            addCriterion("rule_Type <=", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeLike(String value) {
            addCriterion("rule_Type like", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotLike(String value) {
            addCriterion("rule_Type not like", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeIn(List<String> values) {
            addCriterion("rule_Type in", values, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotIn(List<String> values) {
            addCriterion("rule_Type not in", values, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeBetween(String value1, String value2) {
            addCriterion("rule_Type between", value1, value2, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotBetween(String value1, String value2) {
            addCriterion("rule_Type not between", value1, value2, "ruleType");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundIsNull() {
            addCriterion("time_Background is null");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundIsNotNull() {
            addCriterion("time_Background is not null");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundEqualTo(String value) {
            addCriterion("time_Background =", value, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundNotEqualTo(String value) {
            addCriterion("time_Background <>", value, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundGreaterThan(String value) {
            addCriterion("time_Background >", value, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundGreaterThanOrEqualTo(String value) {
            addCriterion("time_Background >=", value, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundLessThan(String value) {
            addCriterion("time_Background <", value, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundLessThanOrEqualTo(String value) {
            addCriterion("time_Background <=", value, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundLike(String value) {
            addCriterion("time_Background like", value, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundNotLike(String value) {
            addCriterion("time_Background not like", value, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundIn(List<String> values) {
            addCriterion("time_Background in", values, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundNotIn(List<String> values) {
            addCriterion("time_Background not in", values, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundBetween(String value1, String value2) {
            addCriterion("time_Background between", value1, value2, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andTimeBackgroundNotBetween(String value1, String value2) {
            addCriterion("time_Background not between", value1, value2, "timeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundIsNull() {
            addCriterion("place_Background is null");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundIsNotNull() {
            addCriterion("place_Background is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundEqualTo(String value) {
            addCriterion("place_Background =", value, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundNotEqualTo(String value) {
            addCriterion("place_Background <>", value, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundGreaterThan(String value) {
            addCriterion("place_Background >", value, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundGreaterThanOrEqualTo(String value) {
            addCriterion("place_Background >=", value, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundLessThan(String value) {
            addCriterion("place_Background <", value, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundLessThanOrEqualTo(String value) {
            addCriterion("place_Background <=", value, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundLike(String value) {
            addCriterion("place_Background like", value, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundNotLike(String value) {
            addCriterion("place_Background not like", value, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundIn(List<String> values) {
            addCriterion("place_Background in", values, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundNotIn(List<String> values) {
            addCriterion("place_Background not in", values, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundBetween(String value1, String value2) {
            addCriterion("place_Background between", value1, value2, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andPlaceBackgroundNotBetween(String value1, String value2) {
            addCriterion("place_Background not between", value1, value2, "placeBackground");
            return (Criteria) this;
        }

        public Criteria andFileurlIsNull() {
            addCriterion("fileUrl is null");
            return (Criteria) this;
        }

        public Criteria andFileurlIsNotNull() {
            addCriterion("fileUrl is not null");
            return (Criteria) this;
        }

        public Criteria andFileurlEqualTo(String value) {
            addCriterion("fileUrl =", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlNotEqualTo(String value) {
            addCriterion("fileUrl <>", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlGreaterThan(String value) {
            addCriterion("fileUrl >", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlGreaterThanOrEqualTo(String value) {
            addCriterion("fileUrl >=", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlLessThan(String value) {
            addCriterion("fileUrl <", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlLessThanOrEqualTo(String value) {
            addCriterion("fileUrl <=", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlLike(String value) {
            addCriterion("fileUrl like", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlNotLike(String value) {
            addCriterion("fileUrl not like", value, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlIn(List<String> values) {
            addCriterion("fileUrl in", values, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlNotIn(List<String> values) {
            addCriterion("fileUrl not in", values, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlBetween(String value1, String value2) {
            addCriterion("fileUrl between", value1, value2, "fileurl");
            return (Criteria) this;
        }

        public Criteria andFileurlNotBetween(String value1, String value2) {
            addCriterion("fileUrl not between", value1, value2, "fileurl");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinIsNull() {
            addCriterion("recommend_People_Min is null");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinIsNotNull() {
            addCriterion("recommend_People_Min is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinEqualTo(Integer value) {
            addCriterion("recommend_People_Min =", value, "recommendPeopleMin");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinNotEqualTo(Integer value) {
            addCriterion("recommend_People_Min <>", value, "recommendPeopleMin");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinGreaterThan(Integer value) {
            addCriterion("recommend_People_Min >", value, "recommendPeopleMin");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("recommend_People_Min >=", value, "recommendPeopleMin");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinLessThan(Integer value) {
            addCriterion("recommend_People_Min <", value, "recommendPeopleMin");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinLessThanOrEqualTo(Integer value) {
            addCriterion("recommend_People_Min <=", value, "recommendPeopleMin");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinIn(List<Integer> values) {
            addCriterion("recommend_People_Min in", values, "recommendPeopleMin");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinNotIn(List<Integer> values) {
            addCriterion("recommend_People_Min not in", values, "recommendPeopleMin");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinBetween(Integer value1, Integer value2) {
            addCriterion("recommend_People_Min between", value1, value2, "recommendPeopleMin");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMinNotBetween(Integer value1, Integer value2) {
            addCriterion("recommend_People_Min not between", value1, value2, "recommendPeopleMin");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxIsNull() {
            addCriterion("recommend_People_Max is null");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxIsNotNull() {
            addCriterion("recommend_People_Max is not null");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxEqualTo(Integer value) {
            addCriterion("recommend_People_Max =", value, "recommendPeopleMax");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxNotEqualTo(Integer value) {
            addCriterion("recommend_People_Max <>", value, "recommendPeopleMax");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxGreaterThan(Integer value) {
            addCriterion("recommend_People_Max >", value, "recommendPeopleMax");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("recommend_People_Max >=", value, "recommendPeopleMax");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxLessThan(Integer value) {
            addCriterion("recommend_People_Max <", value, "recommendPeopleMax");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxLessThanOrEqualTo(Integer value) {
            addCriterion("recommend_People_Max <=", value, "recommendPeopleMax");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxIn(List<Integer> values) {
            addCriterion("recommend_People_Max in", values, "recommendPeopleMax");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxNotIn(List<Integer> values) {
            addCriterion("recommend_People_Max not in", values, "recommendPeopleMax");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxBetween(Integer value1, Integer value2) {
            addCriterion("recommend_People_Max between", value1, value2, "recommendPeopleMax");
            return (Criteria) this;
        }

        public Criteria andRecommendPeopleMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("recommend_People_Max not between", value1, value2, "recommendPeopleMax");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 12 12:16:46 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table room
     *
     * @mbg.generated Sat Jun 12 12:16:46 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}