package com.trpg.version1.mybatis.entity;

import java.io.Serializable;

public class Room implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.roomId
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private Integer roomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.name
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.descri
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private String descri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.type
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.short_Time
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private String shortTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.long_Time
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private String longTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.image_Url
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.time_Background
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private String timeBackground;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.place_Background
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private String placeBackground;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.recommend_People
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private String recommendPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.state
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table room
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.roomId
     *
     * @return the value of room.roomId
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.roomId
     *
     * @param roomid the value for room.roomId
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.name
     *
     * @return the value of room.name
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.name
     *
     * @param name the value for room.name
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.descri
     *
     * @return the value of room.descri
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public String getDescri() {
        return descri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.descri
     *
     * @param descri the value for room.descri
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setDescri(String descri) {
        this.descri = descri == null ? null : descri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.type
     *
     * @return the value of room.type
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.type
     *
     * @param type the value for room.type
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.short_Time
     *
     * @return the value of room.short_Time
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public String getShortTime() {
        return shortTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.short_Time
     *
     * @param shortTime the value for room.short_Time
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setShortTime(String shortTime) {
        this.shortTime = shortTime == null ? null : shortTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.long_Time
     *
     * @return the value of room.long_Time
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public String getLongTime() {
        return longTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.long_Time
     *
     * @param longTime the value for room.long_Time
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setLongTime(String longTime) {
        this.longTime = longTime == null ? null : longTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.image_Url
     *
     * @return the value of room.image_Url
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.image_Url
     *
     * @param imageUrl the value for room.image_Url
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.time_Background
     *
     * @return the value of room.time_Background
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public String getTimeBackground() {
        return timeBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.time_Background
     *
     * @param timeBackground the value for room.time_Background
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setTimeBackground(String timeBackground) {
        this.timeBackground = timeBackground == null ? null : timeBackground.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.place_Background
     *
     * @return the value of room.place_Background
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public String getPlaceBackground() {
        return placeBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.place_Background
     *
     * @param placeBackground the value for room.place_Background
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setPlaceBackground(String placeBackground) {
        this.placeBackground = placeBackground == null ? null : placeBackground.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.recommend_People
     *
     * @return the value of room.recommend_People
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public String getRecommendPeople() {
        return recommendPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.recommend_People
     *
     * @param recommendPeople the value for room.recommend_People
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setRecommendPeople(String recommendPeople) {
        this.recommendPeople = recommendPeople == null ? null : recommendPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.state
     *
     * @return the value of room.state
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.state
     *
     * @param state the value for room.state
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room
     *
     * @mbg.generated Sun Jun 13 17:07:32 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roomid=").append(roomid);
        sb.append(", name=").append(name);
        sb.append(", descri=").append(descri);
        sb.append(", type=").append(type);
        sb.append(", shortTime=").append(shortTime);
        sb.append(", longTime=").append(longTime);
        sb.append(", imageUrl=").append(imageUrl);
        sb.append(", timeBackground=").append(timeBackground);
        sb.append(", placeBackground=").append(placeBackground);
        sb.append(", recommendPeople=").append(recommendPeople);
        sb.append(", state=").append(state);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}