package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.AttributeCharacter;
import com.trpg.version1.mybatis.entity.AttributeCharacterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttributeCharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attributeCharacter
     *
     * @mbg.generated Mon Jun 14 20:23:53 CST 2021
     */
    long countByExample(AttributeCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attributeCharacter
     *
     * @mbg.generated Mon Jun 14 20:23:53 CST 2021
     */
    int deleteByExample(AttributeCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attributeCharacter
     *
     * @mbg.generated Mon Jun 14 20:23:53 CST 2021
     */
    int insert(AttributeCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attributeCharacter
     *
     * @mbg.generated Mon Jun 14 20:23:53 CST 2021
     */
    int insertSelective(AttributeCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attributeCharacter
     *
     * @mbg.generated Mon Jun 14 20:23:53 CST 2021
     */
    List<AttributeCharacter> selectByExample(AttributeCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attributeCharacter
     *
     * @mbg.generated Mon Jun 14 20:23:53 CST 2021
     */
    int updateByExampleSelective(@Param("record") AttributeCharacter record, @Param("example") AttributeCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attributeCharacter
     *
     * @mbg.generated Mon Jun 14 20:23:53 CST 2021
     */
    int updateByExample(@Param("record") AttributeCharacter record, @Param("example") AttributeCharacterExample example);
}