package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.Attribute;
import com.trpg.version1.mybatis.entity.AttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    long countByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int deleteByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int deleteByPrimaryKey(Integer attributeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int insert(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int insertSelective(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    List<Attribute> selectByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    Attribute selectByPrimaryKey(Integer attributeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") Attribute record, @Param("example") AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int updateByExample(@Param("record") Attribute record, @Param("example") AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int updateByPrimaryKeySelective(Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int updateByPrimaryKey(Attribute record);
}