package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.AttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    long countByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int deleteByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int deleteByPrimaryKey(Integer attributeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int insert(com.trpg.version1.mybatis.entity.Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int insertSelective(com.trpg.version1.mybatis.entity.Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    List<com.trpg.version1.mybatis.entity.Attribute> selectByExample(AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    com.trpg.version1.mybatis.entity.Attribute selectByPrimaryKey(Integer attributeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int updateByExampleSelective(@Param("record") com.trpg.version1.mybatis.entity.Attribute record, @Param("example") AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int updateByExample(@Param("record") com.trpg.version1.mybatis.entity.Attribute record, @Param("example") AttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int updateByPrimaryKeySelective(com.trpg.version1.mybatis.entity.Attribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attribute
     *
     * @mbg.generated Wed Jun 02 19:24:22 CST 2021
     */
    int updateByPrimaryKey(com.trpg.version1.mybatis.entity.Attribute record);
}