package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.Character;
import com.trpg.version1.mybatis.entity.CharacterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    long countByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int deleteByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int insert(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int insertSelective(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    List<Character> selectByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int updateByExampleSelective(@Param("record") Character record, @Param("example") CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int updateByExample(@Param("record") Character record, @Param("example") CharacterExample example);
}