package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.ChatGroup;
import com.trpg.version1.mybatis.entity.ChatGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    long countByExample(ChatGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    int deleteByExample(ChatGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    int deleteByPrimaryKey(@Param("chatid") Integer chatid, @Param("roomid") Integer roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    int insert(ChatGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    int insertSelective(ChatGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    List<ChatGroup> selectByExample(ChatGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    ChatGroup selectByPrimaryKey(@Param("chatid") Integer chatid, @Param("roomid") Integer roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    int updateByExampleSelective(@Param("record") ChatGroup record, @Param("example") ChatGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    int updateByExample(@Param("record") ChatGroup record, @Param("example") ChatGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    int updateByPrimaryKeySelective(ChatGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatGroup
     *
     * @mbg.generated Mon May 31 12:20:08 CST 2021
     */
    int updateByPrimaryKey(ChatGroup record);
}