package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.ChatUser;
import com.trpg.version1.mybatis.entity.ChatUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    long countByExample(ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    int deleteByExample(ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    int insert(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    int insertSelective(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    List<ChatUser> selectByExample(ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    int updateByExampleSelective(@Param("record") ChatUser record, @Param("example") ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chatUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    int updateByExample(@Param("record") ChatUser record, @Param("example") ChatUserExample example);
}