package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.Description;
import com.trpg.version1.mybatis.entity.DescriptionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    long countByExample(DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int deleteByExample(DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int deleteByPrimaryKey(Integer descriptionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int insert(Description record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int insertSelective(Description record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    List<Description> selectByExample(DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    Description selectByPrimaryKey(Integer descriptionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int updateByExampleSelective(@Param("record") Description record, @Param("example") DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int updateByExample(@Param("record") Description record, @Param("example") DescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int updateByPrimaryKeySelective(Description record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table description
     *
     * @mbg.generated Wed Jun 02 16:18:03 CST 2021
     */
    int updateByPrimaryKey(Description record);
}