package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.DescriptionCharacter;
import com.trpg.version1.mybatis.entity.DescriptionCharacterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DescriptionCharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table descriptionCharacter
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    long countByExample(DescriptionCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table descriptionCharacter
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    int deleteByExample(DescriptionCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table descriptionCharacter
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    int insert(DescriptionCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table descriptionCharacter
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    int insertSelective(DescriptionCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table descriptionCharacter
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    List<DescriptionCharacter> selectByExample(DescriptionCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table descriptionCharacter
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    int updateByExampleSelective(@Param("record") DescriptionCharacter record, @Param("example") DescriptionCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table descriptionCharacter
     *
     * @mbg.generated Mon Jun 14 22:42:03 CST 2021
     */
    int updateByExample(@Param("record") DescriptionCharacter record, @Param("example") DescriptionCharacterExample example);
}