package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.InfoBoard;
import com.trpg.version1.mybatis.entity.InfoBoardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfoBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    long countByExample(InfoBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    int deleteByExample(InfoBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    int deleteByPrimaryKey(Integer boardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    int insert(InfoBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    int insertSelective(InfoBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    List<InfoBoard> selectByExample(InfoBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    InfoBoard selectByPrimaryKey(Integer boardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") InfoBoard record, @Param("example") InfoBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    int updateByExample(@Param("record") InfoBoard record, @Param("example") InfoBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    int updateByPrimaryKeySelective(InfoBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infoBoard
     *
     * @mbg.generated Mon Jun 14 00:01:38 CST 2021
     */
    int updateByPrimaryKey(InfoBoard record);
}