package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.RoomUser;
import com.trpg.version1.mybatis.entity.RoomUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    long countByExample(RoomUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    int deleteByExample(RoomUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    int insert(RoomUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    int insertSelective(RoomUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    List<RoomUser> selectByExample(RoomUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    int updateByExampleSelective(@Param("record") RoomUser record, @Param("example") RoomUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roomUser
     *
     * @mbg.generated Tue Jun 01 14:04:45 CST 2021
     */
    int updateByExample(@Param("record") RoomUser record, @Param("example") RoomUserExample example);
}