package com.trpg.version1.mybatis.dao;

import com.trpg.version1.mybatis.entity.Skill;
import com.trpg.version1.mybatis.entity.SkillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    long countByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    int deleteByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    int deleteByPrimaryKey(Integer skillid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    int insert(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    int insertSelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    List<Skill> selectByExample(SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    Skill selectByPrimaryKey(Integer skillid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") Skill record, @Param("example") SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    int updateByExample(@Param("record") Skill record, @Param("example") SkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    int updateByPrimaryKeySelective(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skill
     *
     * @mbg.generated Mon Jun 14 20:23:52 CST 2021
     */
    int updateByPrimaryKey(Skill record);
}